//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pekara
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class Artikli
    {
        public int ArtikalID { get; set; }

		[DisplayName("ID kategorije")]
		public int KategorijaID { get; set; }

		[DisplayName("Naziv artikla")]
		public string NazivArtikla { get; set; }

        public Nullable<int> Masa { get; set; }

		[DisplayName("Tip brasna")]
		public string TipBrasna { get; set; }

		[DisplayName("Proizv. cena bez PDV-a")]
        public Nullable<int> ProizvodjackaCenaBezPDV { get; set; }

		[DisplayName("Proizv. cena sa PDV-om")]
		public Nullable<int> ProizvodjackaCenaSaPDV { get; set; }
    }
}
