//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pekara
{
    using System;
    using System.Collections.Generic;
    
    public partial class NalogProizvodnje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NalogProizvodnje()
        {
            this.StavkeNalogaProizvodnjes = new HashSet<StavkeNalogaProizvodnje>();
        }
    
        public int NalogID { get; set; }
        public string BrojNaloga { get; set; }
        public System.DateTime DatumNaloga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkeNalogaProizvodnje> StavkeNalogaProizvodnjes { get; set; }
    }
}
