//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pekara
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	public partial class StavkeNalogaProizvodnje
    {
        public int StavkeNPID { get; set; }

		[DisplayName("Nalog")]
		public int NalogID { get; set; }

		[DisplayName("Artikal")]
		public int ArtikalID { get; set; }

		[DisplayName("Kolicina (kom)")]
		public int Kolicina { get; set; }
    
        public virtual NalogProizvodnje NalogProizvodnje { get; set; }
    }
}
