//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Pekara
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VG_DatabaseEntities : DbContext
    {
        public VG_DatabaseEntities()
            : base("name=VG_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikli> Artiklis { get; set; }
        public virtual DbSet<Kategorije> Kategorijes { get; set; }
        public virtual DbSet<NalogProizvodnje> NalogProizvodnjes { get; set; }
        public virtual DbSet<StavkeNalogaProizvodnje> StavkeNalogaProizvodnjes { get; set; }
    
        
    
        
    
        
    
        public virtual ObjectResult<GetNalSt_Result> GetNalSt()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNalSt_Result>("GetNalSt");
        }
    }
}
